### ISSUE TITLE
Empty value for input

### ISSUE THREAD

**Issue by playinteractive** [linna/csrf-guard#8]
Hi,

The value for the hidden input is always empty:

`<input type="hidden" name="csrf_ce4f2adca1a28427" value="" />`

Name property works fine.

Could you check it?

Thanks

**Comment by peter279k** [comment]
@playinteractive, thank you for your reply. Consider the following code:

```php
<?php

require 'vendor/autoload.php';

use Linna\CsrfGuard;

session_start();

//example:
//create new csrf instance with
//64 token stored
//32 byte token length
$csrf = new CsrfGuard(64, 32);

$token = $csrf->getToken();

var_dump($token);
```

And the result is like that following bock:

```
array(2) {
  'name' =>
  string(21) "csrf_24f9e17864471f72"
  'value' =>
  string(64) "a1fa969415c0c02f2375e7809583d6091898569297b046ba9998c4ae462e4c28"
}
```
According to the usage section in [README.md](https://github.com/linna/csrf-guard#usage), using `$token['token']` to get the token value.

I think it's undefined index `token` in this `$token`  associate array and it should be change into `$token['value']`.

I think it's the typo problem. @s3b4stian, you need to consider this and fix this typo in `README.md` :+1: .

**Comment by s3b4stian** [comment]
Sorry for this mistake! I fix it!

**Comment by s3b4stian** [comment]
README.md updated 👍

**Comment by playinteractive** [comment]
With `$token['value']` works perfect!

Thanks s3b4stian

**Comment by s3b4stian** [comment]
Thanks to you for reporting the bug!
